config/routes.rb
Hugo::Application.routes.draw do
  resources :users

  resources :messages
  root :to => 'users#new'



end

app/models/message.rb
class Message
  include Mongoid::Document
  field :sid, type: String
  field :account_sid, type: String
  field :from, type: Integer
  field :status, type: String
  field :direction, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name
  field :number

  validates_presence_of :name
  validates_presence_of :number

  before_create :remove_dashes
  after_create :send_first_text


  protected

  def remove_dashes
    self.number = self.number.to_s.gsub(/[^0-9]/, "")
  end

  def send_first_text
    
  end

end

app/models/venue.rb
class Venue
  include Mongoid::Document

  field :neighborhood, type: Hash
  field :power_outage_percentage, type: Integer

  def self.location_search(zip, from_number)
    query = "hotel"
    # Connect to 4SQ
    client = Foursquare2::Client.new(:client_id => 'SMPGEQCWEVNRIF3UQTYOQSTXCD5VPAPNWLYD2O04XPUIBVCE', :client_secret => 'SARCGLTZZFM4WBOSZSNLJPNFVMDFQPWAVWW1ZLETDST5HFBD')
    # Search 4SQ Explore for stuff
    response = client.explore_venues(near: "#{zip}", :query => "#{query}", limit: "50")
    response_items = response.groups.first.items
    # Grab just the venue info
    venues = response_items.collect{|item| item.venue }
    # Grab the neighborhoods from ConEd
    report = Sandy::Provider::ConEd::Report.new
    neighborhoods = report.neighborhoods
    places = []
    # iterate through venues adding in power information
    venues.each do |venue|
      # we dont want locations without numbas!
      unless venue.contact['formattedPhone'].blank?
        # Object to store place data
        place = OpenStruct.new
        place.marshal_load(venue)
        venue_location = [venue.location["lat"], venue.location["lng"]]
        # iterate through each neighborhood finding the closest one to the venue location. 
        hoods = []
        neighborhoods.each do |hood|
          if hood.latitude.blank? || hood.longitude.blank?
          else
            distance = Geocoder::Calculations.distance_between(venue_location, [hood.latitude, hood.longitude])
            new_hood = {name: hood.name, customers_affected: hood.customers_affected, total_customers: hood.total_customers, estimated_recovery_time: hood.estimated_recovery_time, distance: distance}
            hoods << new_hood
          end
        end
        # below is the most likely
        hood = hoods.flatten.sort_by{|hood| hood[:distance]}.first
        # calculate the percentage of people without power
        power_outage_percentage = (hood[:customers_affected].to_f / hood[:total_customers].to_f) * 100
        # round that shit off
        power_outage_percentage = power_outage_percentage.ceil
        # Add power info to the place struct
        place.power_outage_percentage = power_outage_percentage
        place.neighborhood = hood
        places << place
      end
    end
    # Prioritize the hotels with the most likelihood of power
    places.sort_by{|place| place.power_outage_percentage}
    # Only show the user the best 5
    alerted_places = places.first(5)
    Telapi.config do |config|
      config.account_sid = 'ACbbcf2b79541543ff86dd9955952d1076'
      config.auth_token  = 'bc039f3d301a4475899cb9e31cb3d953'
    end
    # #{venue.contact['formattedPhone']}"
    alerted_places.each do |venue|
     Telapi::Message.create( "#{from_number}", '(302) 752-4624', "#{venue.name}\n#{venue.location['address']}\n#{venue.location.city}, #{venue.location.state} #{venue.location['postalCode']}\n(845) 797-9516" )
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    
    body = params['Body'].gsub(/[^0-9]/, "")
    from = params['From']

    Venue.location_search(body, from)

    respond_to do |format|
      format.xml
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users/1
  # GET /users/1.json
  def show

  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end


  def create
    @user = User.new(params[:user])

    Telapi.config do |config|
      config.account_sid = 'ACbbcf2b79541543ff86dd9955952d1076'
      config.auth_token  = 'bc039f3d301a4475899cb9e31cb3d953'
    end
    Telapi::Message.create( "#{@user.number}", '(302) 752-4624', "Hi, I'm Hugo! Thanks for signing up, #{@user.name}. Send me your zip code and I'll send you some hotels with pppowweerrrrrrrrrrrr!" )

    # respond_to do |format|
    #   if @user.save
    #     format.html { redirect_to @user, notice: 'User was successfully created.' }
    #     format.json { render json: @user, status: :created, location: @user }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hugo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sid %><br />
    <%= f.text_field :sid %>
  </div>
  <div class="field">
    <%= f.label :account_sid %><br />
    <%= f.text_field :account_sid %>
  </div>
  <div class="field">
    <%= f.label :from %><br />
    <%= f.number_field :from %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :direction %><br />
    <%= f.text_field :direction %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Sid</th>
    <th>Account sid</th>
    <th>From</th>
    <th>Status</th>
    <th>Direction</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.sid %></td>
    <td><%= message.account_sid %></td>
    <td><%= message.from %></td>
    <td><%= message.status %></td>
    <td><%= message.direction %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sid:</b>
  <%= @message.sid %>
</p>

<p>
  <b>Account sid:</b>
  <%= @message.account_sid %>
</p>

<p>
  <b>From:</b>
  <%= @message.from %>
</p>

<p>
  <b>Status:</b>
  <%= @message.status %>
</p>

<p>
  <b>Direction:</b>
  <%= @message.direction %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users/create.html.erb
<div class="container signup">
  <div class="row">
    <div class="span6 offset3">
      <h1 class="brand-title">Thanks!</h1>
      <p class="highlight">HUGO should be texting you shortly.</p>
    </div><!-- .span6 -->
  </div><!-- .row -->
</div><!-- .container --> 

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.number %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container signup">
  <div class="row">
    <div class="span6 offset3">
      <h1 class="brand-title">HUGO.</h1>
      <p class="highlight">HUGO is here you when you need him- just text him.</p>
      <%= form_for @user, html: {class: "goodtogo"} do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
        <fieldset>
          <%= f.text_field :name, placeholder: "Your Name", class: "span6 goodtogo1" %>
          <%= f.telephone_field :number, placeholder: "5555555555", class: "span6 goodtogo2" %>
          <div class="row">
            <button class="btn btn-primary span6">Use HUGO.</button>
          </div><!-- .row -->
        </fieldset>
      <% end %>
    </div><!-- .span6 -->
  </div><!-- .row -->
</div><!-- .container --> 

app/views/users/show.html.erb
<div class="container signup">
  <div class="row">
    <div class="span6 offset3">
      <h1 class="brand-title">Thanks!</h1>
      <p class="highlight">HUGO should be texting you shortly.</p>
    </div><!-- .span6 -->
  </div><!-- .row -->
</div><!-- .container --> 